[tool.poetry]
name = "pySigma-backend-panther"
version = "0.1.0"
description = "pySigma backend for Panther"
authors = ["Josh Esbrook <jehockey@umich.edu>"]
license = "LGPL-3.0-only"
repository = "https://github.com/jehockey/pySigma-backend-panther"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.8.12"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
coverage = "^7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
