name: Tag with Latest Version on PR Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: |
          pip install --upgrade pip poetry
      - name: Set up Git
        run: |
          git config user.name "dac-bot[bot]"
          git config user.email "dac-bot@panther.com"
      - name: Check and update tag
        run: |
          VERSION="v$(poetry version --short)"
          
          if [[ $(git tag -l $VERSION) ]]; then
            echo "Tag $VERSION already exists"
          else
            echo "Tagging with $VERSION"
            git tag "$VERSION"
            git push origin --tags
          fi