name: Test
on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run lint
        run: poetry run black --check . &&  poetry run isort --check-only .
      - name: Run tests
        run: poetry run pytest --cov=sigma --cov-report term --cov-report xml:cov.xml -vv
