name: Test
on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run lint
        run: poetry run black --check . &&  poetry run isort --check-only .
      - name: Run tests
        run: poetry run pytest --cov=sigma --cov-report term --cov-report xml:cov.xml -vv
